image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      composer install
      cp .env.example .env || true
      php artisan key:generate
      touch database/database.sqlite
      php artisan migrate
      npm install
  - command: |
      php artisan serve --host=0.0.0.0 --port=8000

  - command: |
      npm run dev

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5173
    onOpen: ignore
